const FETCH_USER='FETCH_USER';
const SET_USER='SET_USER';
const FETCH_USER_INFO = 'FETCH_USER_INFO';
const SET_USER_INFO = 'SET_USER_INFO';
// export const FETCH_PRODUCTS='FETCH_PRODUCTS';
// export const SET_PRODUCTS ='SET_PRODUCTS';
const RECEIVE_ERRORS = "RECEIVE_ERRORS";
const CLEAR_ERRORS = "CLEAR_ERRORS";



export default{
    // FETCH_PRODUCTS,
    FETCH_USER,
    FETCH_USER_INFO,
    // SET_PRODUCTS,
    SET_USER,
    SET_USER_INFO,
    RECEIVE_ERRORS,
    CLEAR_ERRORS
}