const FETCH_USER='FETCH_USER';
const SET_USER='SET_USER';
const FETCH_PRODUCTS='FETCH_PRODUCTS';
const SET_PRODUCTS ='SET_PRODUCTS';
export const RECEIVE_ERRORS = "RECEIVE_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export default{
    FETCH_PRODUCTS,
    FETCH_USER,
    SET_PRODUCTS,
    SET_USER,
    RECEIVE_ERRORS,
    CLEAR_ERRORS
}